# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: storage-volume
              mountPath: /data  # Mount path inside the container
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
