apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-service-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-service-bus
  template:
    metadata:
      labels:
        app: deploy-service-bus
    spec:
      containers:
        - name: deploy-service-bus
          image: nginx:latest
            # image: mcr.microsoft.com/azure-service-bus/azure-service-bus:latest
            # image: your-custom-application-image:latest
          ports:
            # - containerPort: 80  # Example port 80 for HTTP traffic
            - containerPort: 5671  # AMQP port
              protocol: TCP
          env:
            - name: CONNECTION_STRING
              value: "Endpoint=sb://keda-order-processor.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=JZCymAew/wONdVcvPcrahVpjV21XeKUtX+ASbO8ATYY="

          volumeMounts:
            - mountPath: "/mnt/azure"
              name: azure-storage
      volumes:
        - name: azure-storage
          persistentVolumeClaim:
            claimName: azure-file-pvc
