apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-service-bus-triggerauth
spec:
  secretTargetRef:
    - parameter: connectionString
      name: azure-service-bus-credentials
