apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-rabbitmq-parser
spec:
  secretTargetRef:
  - parameter: host
    name: rabbitmq-secret
    key: host

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: parserservice-scaledobject
spec:
  cooldownPeriod: 120
  scaleTargetRef:
    name: parserservice  # Replace with your deployment name
    kind: Deployment
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: fileParseQueue
      mode: QueueLength
      value: "10"
    authenticationRef:
      name: trigger-auth-rabbitmq-parser
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: fileParseCompleteQueue
      mode: QueueLength
      value: "10"
    authenticationRef:
      name: trigger-auth-rabbitmq-parser
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: eventLogQueue
      mode: QueueLength
      value: "10"
    authenticationRef:
      name: trigger-auth-rabbitmq-parser