apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-rabbitmq-events
spec:
  secretTargetRef:
  - parameter: host
    name: rabbitmq-secret
    key: host

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: eventservice-scaledobject  
spec:
  cooldownPeriod: 120  
  scaleTargetRef:
    name: eventservice  # Replace with your deployment name
    kind: Deployment 
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: dev_queue  
      mode: QueueLength
      value: "10"  # Target backlog or publish/sec per instance
    authenticationRef:
      name: trigger-auth-rabbitmq-events
