apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-rabbitmq-analyser
spec:
  secretTargetRef:
  - parameter: host
    name: rabbitmq-secret
    key: host

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analyserservice-scaledobject
spec:
  cooldownPeriod: 120
  scaleTargetRef:
    name: analyserservice  # Replace with your deployment name
    kind: Deployment
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: functionLinkingCompleteQueue  
        mode: QueueLength
        value: "10"
      authenticationRef:
        name: trigger-auth-rabbitmq-analyser
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: analysisCompleteQueue  # Replace with your additional queue name
        mode: QueueLength
        value: "10"  # Adjust the threshold as needed
      authenticationRef:
        name: trigger-auth-rabbitmq-analyser
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: eventLogQueue  # Replace with your additional queue name
        mode: QueueLength
        value: "10"  # Adjust the threshold as needed
      authenticationRef:
        name: trigger-auth-rabbitmq-analyser
