apiVersion: apps/v1
kind: Deployment
metadata:
  name: parserservice
  labels:
    app: parserservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parserservice
  template:
    metadata:
      labels:
        app: parserservice
    spec:
      containers:
      - name: parserservice
        image: rapidxccdev.azurecr.io/parserservice:latest
        
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: dev
        - name: RABBITMQ_URL
          value: amqps://lxptmxtz:xuBCHtJkSOBnUUHYcI8hht9A3uw1G_Dy@puffin-01.rmq2.cloudamqp.com/lxptmxtz
        - name: POSTGRES_URL
          value: postgresql+psycopg://citus:Codescout123@c-gen-ai-test-db.xyr2br6ljuwsr7.postgres.cosmos.azure.com:6432/rapidx
        - name: NEO4j_URI
          value: bolt://codescout-neo4j-dev.southindia.cloudapp.azure.com:7687/neo4j
        - name: NEO4j_USERNAME
          value: neo4j
        - name: NEO4j_PASSWORD
          value: Codescout123
        - name: FILE_PARSE_QUEUE_NAME
          value: fileParseQueue
        - name: FILE_PARSE_COMPLETE_QUEUE_NAME
          value: fileParseCompleteQueue
        - name: EVENT_LOG_QUEUE_NAME
          value: eventLogQueue
        - name: PARSER_NO_OF_LINES
          value: "10"
        - name: PARSER_NO_OF_LINES_TOP
          value: "10"
        - name: PARSER_NO_OF_LINES_BOTTOM
          value: "2"
        volumeMounts:
        - name: storage
          mountPath: /mnt/storage

      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: azurefile

      imagePullSecrets:
      - name: acr-credentials
