apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitorservice
  labels:
    app: monitorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitorservice
  template:
    metadata:
      labels:
        app: monitorservice
    spec:
      containers:
      - name: monitorservice
        image: rapidxccdev.azurecr.io/monitorservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: dev
        - name: POSTGRES_URL
          value: postgresql+psycopg://citus:Codescout123@c-gen-ai-test-db.xyr2br6ljuwsr7.postgres.cosmos.azure.com:6432/rapidx
        - name: RABBITMQ_URL
          value: amqps://lxptmxtz:xuBCHtJkSOBnUUHYcI8hht9A3uw1G_Dy@puffin-01.rmq2.cloudamqp.com/lxptmxtz
        - name: NEO4j_URI
          value: bolt://codescout-neo4j-dev.southindia.cloudapp.azure.com:7687/neo4j
        - name: NEO4j_USERNAME
          value: neo4j
        - name: NEO4j_PASSWORD
          value: Codescout123
        - name: FILE_PARSE_COMPLETE_QUEUE_NAME
          value: fileParseCompleteQueue
        - name: REPO_PARSE_COMPLETE_QUEUE_NAME
          value: repoParseCompleteQueue
        - name: EVENT_LOG_QUEUE_NAME
          value: eventLogQueue

      imagePullSecrets:
      - name: acr-credentials
