apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventservice
  labels:
    app: eventservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventservice
  template:
    metadata:
      labels:
        app: eventservice
    spec:
      containers:
      - name: eventservice
        image: rapidxccdev.azurecr.io/eventservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: dev
        - name: EVENT_LOG_QUEUE_NAME
          value: dev_queue
        # - name: POSTGRES_URL
        #   value: postgresql+psycopg2://citus:Codescout123@c-gen-ai-test-db.xyr2br6ljuwsr7.postgres.cosmos.azure.com:6432/rapidx
        # - name: RABBITMQ_URL
        #   value: amqps://lxptmxtz:xuBCHtJkSOBnUUHYcI8hht9A3uw1G_Dy@puffin-01.rmq2.cloudamqp.com/lxptmxtz

      imagePullSecrets:
      - name: acr-credentials
