############################################
# article referenced: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume
############################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: rg-codescout-dev-appuser
    volumeAttributes:
      resourceGroup: rg-codescout-dev
      shareName: dev-parser-fs
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - nosharesock
  - nobrl