apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  mountOptions:
    - dir_mode=0755
    - file_mode=0644
  azureFile:
    secretName: azure-secret
    shareName: dev-parser-fs
    readOnly: false
