############################################
# article referenced: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume
############################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile-csi
  volumeMode: Filesystem
  volumeName: azurefile