apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: default
data:
  host: YW1xcHM6Ly9seHB0bXh0ejp4dUJDSHRKa1NPQm5VVUhZY0k4aGh0OUEzdXcxR19EeUBwdWZmaW4ucm1xMi5jbG91ZGFtcXAuY29tL2x4cHRteHR6

  # amqps://lxptmxtz:xuBCHtJkSORnUUHYcI8hhht9A3uw1G_Dy\x00puffin-01.rmq2.cloudamqmp.com/lxptmxtz