apiVersion: v1
kind: Service
metadata:
  name: reposervice
spec:
  selector:
    app: reposervice
  ports:
    - protocol: TCP
      port: 80       # The port that will be exposed outside the service
      targetPort: 80 # The port on the container where the application is running
  type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
